# Generated by Django 4.1.7 on 2023-02-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP_ESPORTS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(default='', max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='director',
            name='birthday',
        ),
        migrations.AddField(
            model_name='director',
            name='birthdate',
            field=models.DateField(default=None),
        ),
    ]
